#
# Groupes de lumières
#
# Chambre des maîtres

- platform: group
  name: "Lampe de chevets groupe de lumières"
  unique_id: philips_lampe_chevet
  entities:
    - light.chevet_1
    - light.chevet_2
    - light.chevet_3
    - light.chevet_4

# Salon

- platform: group
  name: "Lampes Salon groupe de lumières"
  unique_id: philips_lumiere_salon
  entities:
    - light.salon_1
    - light.salon_2
    - light.salon_3

# Extérieure

- platform: group
  name: "Galerie avant groupe de lumières"
  unique_id: philips_lumiere_galerie_avant
  entities:
    - light.galerie_1
    - light.galerie_2

- platform: group
  name: "Lampadaire groupe de lumières"
  unique_id: philips_lumiere_lampadaire
  entities:
    - light.lampadaire_1
    - light.lampadaire_2
    - light.lampadaire_3

- platform: group
  name: "Extérieure avant groupe de lumières"
  unique_id: philips_lumiere_galerie_lampadaire
  entities:
    - light.galerie_1
    - light.galerie_2
    - light.lampadaire_1
    - light.lampadaire_2
    - light.lampadaire_3

# Sous-Sol

- platform: group
  name: "Escalier Sous-sol groupe de lumières"
  unique_id: philips_lumiere_escalier_sous_sol
  entities:
    - light.escalier_sous_sol_1
    - light.escalier_sous_sol_2
    - light.escalier_sous_sol_3
    - light.escalier_sous_sol_4

- platform: group
  name: "Salle familiale groupe de lumières"
  unique_id: philips_lumiere_salle_familiale
  entities:
    - light.familiale_1
    - light.familiale_2
    - light.familiale_3
    - light.familiale_4
    - light.familiale_5
    - light.familiale_6
    - light.familiale_7
    - light.familiale_8
    - light.familiale_9
