button_card_templates: #these are our templates
  titre: #this is my template for section titles, it is very simple, I wont comment it all
    styles:
      card:
        - height: 50px
        - padding-top: 55px
        - margin-top: 5px
        - border: none
        - background: none
      img_cell:
        - align-self: start
        - text-align: start
      name:
        - justify-self: start
        - padding-left: 10px
        - text-transform: lowercase
        - null
        - font-size: 25px
        - letter-spacing: 0.7em
    card_mod:
      style: |
        ha-card {
          --primary-text-color: rgb(var(--my-grey));   
        }
  light: #these is my main template for on/off buttons
    size: 35% #icon size
    show_state: true #we want to show the state
    tap_action:
      haptic: heavy #heavy haptic feedback when clicking on it
      action: toggle #clicking on it will toggle the wsitch
    styles:
      icon:
        - color: rgb(var(--my-grey),0.8) #icon color (my-grey is defined in the theme file)
      card:
        - width: 120px #button width
        - height: 120px #button height
        - margin: auto
      grid:
        - grid-template-areas: '"i" "n" "s"' #layout grid for the various items of the button: Image, Name and State
        - grid-template-columns: 1fr
        - grid-template-rows: 1fr min-content min-content
      img_cell: #Simply the alignment of the icon
        - align-self: start
        - text-align: start
        - justify-content: start
        - padding-left: 15px
      name: #name format
        - justify-self: start #we start from the left
        - padding-left: 12px #we leave a 12px padding from the ledt
        - font-weight: bold #bold font
        - text-transform: lowercase #I like lower case!
        - letter-spacing: 0.2em #I also like increasing the spacing between the letters
        - font-size: 17px #font size
        - padding-bottom: 2px #small padding fromn the bottom
      state: #Formatting the state
        - justify-self: start
        - padding-left: 12px
        - font-weight: bold
        - text-transform: lowercase
        - letter-spacing: 0.2em
        - font-size: 12px
        - opacity: 0.6
        - padding-bottom: 5px
        - opacity: 0.6
    state: #state defined formatting
      - value: 'on' #when state is ON
        styles:
          icon:
            - color: rgb(var(--my-orange)) #The icon will turn orange
          card:
            - background-color: rgba(var(--my-orange),0.2) #background color will rurn orange as well
            - box-shadow: var(--my-box-shadow) #shadow will be an inlay shadow (defined in the theme file)
    card_mod: #default card style
      class: soft-ui #use the card style defined in the theme yaml file
      style: |
        ha-card {
          --primary-text-color: rgb(var(--my-grey));    
        }
  sensor:
    size: 40%
    show_state: true
    tap_action:
      haptic: heavy
      action: toggle
    styles:
      card:
        - width: 80px
        - height: 80px
        - border-radius: 40px
        - box-shadow: rgba(var(--my-orange), 0.3) 0px -50px 36px -28px inset;
        - border: none
      icon:
        - color: rgba(var(--my-orange), 1)
      grid:
        - grid-template-areas: '"n" "i" "s"'
        - grid-template-rows: min-content 40px min-content
      name:
        - width: 80px
        - height: 20px
        - font-size: 14px
        - font-weight: light
        - letter-spacing: 0.1em
      img_cell: null
      state:
        - font-size: 14px
        - justify-self: bottom
        - text-align: center
        - letter-spacing: 0.2em
        - font-weight: bold
    card_mod:
      style: |
        ha-card {
          --primary-text-color: rgb(var(--my-grey));   
        }
  aspirateur:
    size: 35%
    show_state: true
    tap_action:
      haptic: heavy
      action: more-info
    styles:
      icon:
        - color: rgb(var(--my-grey),0.8)
      card:
        - width: 120px
        - height: 120px
        - margin: auto
      grid:
        - grid-template-areas: '"i" "n" "s"'
        - grid-template-columns: 1fr
        - grid-template-rows: 1fr min-content min-content
      img_cell:
        - align-self: start
        - text-align: start
        - justify-content: start
        - padding-left: 15px
      name:
        - justify-self: start
        - padding-left: 12px
        - font-weight: bold
        - text-transform: lowercase
        - letter-spacing: 0.2em
        - font-size: 17px
        - padding-bottom: 2px
      state:
        - justify-self: start
        - padding-left: 12px
        - font-weight: bold
        - text-transform: lowercase
        - font-size: 12px
        - opacity: 0.6
        - letter-spacing: 0.2em
        - padding-bottom: 5px
        - opacity: 0.6
    state:
      - value: cleaning
        styles:
          icon:
            - color: rgb(var(--my-orange))
            - animation: rotating 2s ease infinite
          card:
            - background-color: rgba(var(--my-orange),0.2)
            - box-shadow: var(--my-box-shadow)
    card_mod:
      class: soft-ui
      style: |
        ha-card {
          --primary-text-color: rgb(var(--my-grey));   
  button_single:
    show_state: true
    styles:
      icon:
        - color: rgba(var(--my-blue),0.8)
      card:
        - width: 120px
        - height: 120px
        - margin: auto
      grid:
        - grid-template-areas: '"i" "n" "s"'
        - grid-template-columns: 1fr
        - grid-template-rows: 1fr min-content min-content
      img_cell:
        - align-self: start
        - text-align: start
        - justify-content: start
        - padding-left: 15px
      name:
        - justify-self: start
        - padding-left: 12px
        - font-weight: bold
        - text-transform: lowercase
        - letter-spacing: 0.2em
        - font-size: 17px
        - padding-bottom: 2px
      state:
        - justify-self: start
        - padding-left: 12px
        - font-weight: bold
        - font-size: 12px
        - opacity: 0.6
        - letter-spacing: 0.2em
        - padding-bottom: 5px
        - opacity: 0.6
    card_mod:
      class: soft-ui
      style: |
        ha-card {
          --primary-text-color: rgb(var(--my-grey));   
        }
  frame:
    color_type: label-card
    styles:
      card:
        - padding: 0
        - background-color: transparent
        - opacity: 100%
        - margin: 0 auto
      grid:
        - grid-template-areas: '"buttons"'
        - grid-template-columns: 1fr
        - grid-template-rows: 1fr min-content min-content
      custom_fields:
        buttons:
          - margin: 0
          - padding: 0.5em
          - position: relative
          - left: 0
views:
  - title: home
